# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec06596f596d80e3af90e96dea30a7cc05545247fa50ee05d59c6ba0b4e29b7e0ead2bd3e7d555d8d9e39b45178a2e5b068ac8e4a9071ae0c90846dbca612977

test:
  secret_key_base: 8a710ebca910369b3b81b5bb1e7c93d5d41389795e56c721d6943371b247e4de3bc6453aabe31fdd28e9d158f81f887f62cb50ac1d00e29d3b3cedbe3dc0879f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
